# Generated by Django 6.1.1 on 2026-09-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_newsitem_image_url_charfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='newsitem',
            new_name='news_app_ne_categor_4e6c18_idx',
            old_name='news_app_ne_categor_1d2a0a_idx',
        ),
        migrations.RenameIndex(
            model_name='newsitem',
            new_name='news_app_ne_importa_3db24f_idx',
            old_name='news_app_ne_importa_ef8a3a_idx',
        ),
        migrations.RenameIndex(
            model_name='newsview',
            new_name='news_app_ne_news_it_9fc1e6_idx',
            old_name='news_app_ne_news_it_8d6b0b_idx',
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
