# Generated by Django 6.1.1 on 2026-09-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0010_newsitem_image_source_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='image_source_url',
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
