# Generated by Django 6.1.1 on 2026-09-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0013_alter_newsitem_video_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='video_credit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
